<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DumpLens.App.ViewModels\DumpLens.App.ViewModels.csproj" />
    <ProjectReference Include="..\DumpLens.Application\DumpLens.Application.csproj" />
    <ProjectReference Include="..\DumpLens.Persistence\DumpLens.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
